# Generated by Django 4.0.5 on 2022-06-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGuarderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebe',
            name='edad',
            field=models.IntegerField(verbose_name='edad (meses)'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad (kg)'),
        ),
    ]
